/** 品牌中文俗称 → Bangumi 搜索用名（日文/英文），用于 searchWeb 查询扩展 */
export const COMPANY_SEARCH_ALIASES: Record<string, string[]> = {
  '柚子社': ['ゆずソフト', 'Yuzu-Soft'],
  'Key社': ['Key'],
  '型月': ['Type-Moon', 'TYPE-MOON'],
  '八月社': ['August'],
  '叶子社': ['Leaf'],
  '中二社': ['Minori'],
  '枕社': ['枕', 'Makura'],
  '音符社': ['ensemble'],
  '漩涡社': ['Whirlpool'],
  '方糖社': ['Lump of Sugar'],
  '戏画': ['GIGA', '戯画'],
  'ALICESOFT': ['Alice Soft', 'アリスソフト'],
  'Eushully': ['エウシュリー'],
  'Frontwing': ['フロントウイング'],
  'SAGAPLANETS': ['サガプラネッツ'],
  'CUBE': ['CUBE'],
  'Navel': ['ナベル'],
  '紫社': ['Purple Software'],
  '大枪社': ['Lump of Sugar'],
  '水晶社': ['Crystal-soft'],
  '柚子': ['ゆずソフト', 'Yuzu-Soft'],
  'Key': ['Key'],
};

/** 制作商/品牌 → 旗下作品 */
export const PRODUCER_GAMES: Record<string, string[]> = {
  '柚子社': ['天使的星期日'],
  'Key': ['CLANNAD', 'Rewrite', '夏日口袋', '星之终途', 'Kanon', '星空的记忆 -Wish upon a shooting star'],
  'Type-Moon': ['月姬', '月姬 -A piece of blue glass moon-'],
  'Eushully': ['战女神ZERO', '神采炼金大师', '魔导巧壳', '天结城堡大师'],
  'Alice Soft': ['兰斯03 利萨斯陷落', '兰斯10 决战', '战国兰斯', '多娜多娜 一起干坏事吧'],
  'Navel': ['我们没有翅膀', 'SHUFFLE'],
  'CUBE': ['五彩斑斓的世界'],
  '紫社': ['天津罪', '冥契的牧神节'],
  'SAGAPLANETS': ['金辉恋曲四重奏', '金辉恋曲四重奏 -Golden Time-', '初雪樱'],
  'Frontwing': ['灰色的乐园'],
  '戏画': ['BALDR SKY Dive2 "RECORDARE"', 'BALDR HEART', '女仆咖啡帕露菲'],
};
